### ISSUE TITLE
Oct 2022  workshop - TODO

### ISSUE THREAD

**Issue by tavareshugo** [cambiotraining/hpc-intro-sanger#1]
- [x] Copy newer version of https://github.com/cambiotraining/hpc-intro/blob/main/images/tool_overview.svg
- [x] Update course data and generate link from Dropbox
- [x] Check if steps requesting memory in LSF section need to be removed (including exercise 1 and 2)
- [x] `module load bowtie2` - need to check with guest account!
  - Plan A - we hope it works
  - Plan B - we create script that exports `$MODULEPATH` varibale with CASM path (same as Chloe) to `.bashrc`
  - Plan C - compile `bowtie2` and add it to the PATH
- [x] Need to install `argparse` interactively with them. 
- [x] Need to use `R CMD BATCH` instead of `RScript`

----

Memory issue on gen3:

- cannot be specified with `-m` and `-r`
- at the moment we don't know how much memory is being requested
